### ISSUE TITLE
Atom hangs when no makefile is found

### ISSUE THREAD

**Issue by Teo-ShaoWei** [tasnad/atom-build-make-file#1]
When I attempt to run `Build: Select Active Target` when the active file's folder has no makefiles, Atom will hang.

A desirable behaviour may be to return no build targets, or go up the directory tree and attempt to find a makefile of the ancestor directories.

**Comment by tasnad** [comment]
Hi,
I can't reproduce this. It should give you a dummy target which states that there is no makefile in the file's folder.
Could you tell me how I can reproduce the error?

**Comment by Teo-ShaoWei** [comment]
Hi @tasnad, side note first: thanks for the cool package. I have good productivity with it so far despite the issue. Kudos to you!

Let's see... I have:-
- macOS Sierra v10.12.3
- Atom v1.11.1
- `build` v0.67.0
- `build-make-file` v0.2.2

I can reach the dummy target if I press `F9` or `Build:Trigger` when I open up a new Atom instance and immediately open any file in any folder without makefiles.

But subsequently `F9` only runs the previous job, even though I have moved on to other folders and files. So I usually press `F7` to run `Build: Select Active Target` so the build job can be updated to the folder of the current file in focused in Atom.

If I do `F7` in a folder without makefiles, Atom will hang...

**Comment by tasnad** [comment]
Thanks :)
Ok, I managed to reproduce the error, but it seems to be cause by the build package. 
Have you tried with build-make-file disabled? I still get the error then.

**Comment by Teo-ShaoWei** [comment]
Ah yes, I found it [here](https://github.com/noseglid/atom-build/issues/484).

You are right. I think we can close this issue then.

**Comment by tasnad** [comment]
Ok, thanks for digging that out!
