### ISSUE TITLE
allow for target selection

### ISSUE THREAD

**Issue by anaderi** [tasnad/atom-build-make-file#2]
would be nice to specify & build any but default target.

**Comment by tasnad** [comment]
Hi,
I'm not sure what you mean. You will get all targets in the makefile (rteturned by "make -prRn") - you can see and select them with F7.
Did I get you wrong?

**Comment by anaderi** [comment]
as I press F7 nothing happens (Mac OS X), what is the corresponding command in the command palette?

**Comment by tasnad** [comment]
It should be:
Build: Select Active Target

**Comment by anaderi** [comment]
unfortunately there is nothing alike:

https://picpig.com/7y53lveifu.png

**Comment by tasnad** [comment]
Did you also install the "build" package? (https://atom.io/packages/build)

**Comment by anaderi** [comment]
after `build` installation it became possible to switch target, but now how do I toggle `make` output? (Ctrl-Shift-R seems to be toggling some other window)

**Comment by tasnad** [comment]
Should be called "build: toggle panel". F8 for me, I've no clue for mac.

**Comment by anaderi** [comment]
ah, works fine, indeed. seems like it clashed with https://github.com/fiveisprime/atom-make-runner
